import type { Player } from './types'

// 2025 NFL Season Projections (PPR, 17 games)
// VBD baselines: QB=292, RB=92, WR=110, TE=118
// Trade values calibrated to positional scarcity

const rawPlayers: Omit<Player, 'drafted' | 'onMyTeam'>[] = [
  // ─── QUARTERBACKS ────────────────────────────────────────────────
  {
    id: 'josh-allen',
    name: 'Josh Allen',
    team: 'BUF',
    position: 'QB',
    age: 29,
    bye: 7,
    rank: 12,
    posRank: 1,
    tier: 1,
    adp: 4.5,
    projPts: 438,
    vbd: 146,
    tradeValue: 92,
    injuryRisk: 'Medium',
    upside: 'Ceiling',
    status: 'Active',
    notes: 'Elite dual-threat QB1. Top-5 pick in all formats. Rushing upside makes him truly unmatched.',
    snapPct: 100,
    scheduleRating: 7,
    playoffRating: 8,
  },
  {
    id: 'jalen-hurts',
    name: 'Jalen Hurts',
    team: 'PHI',
    position: 'QB',
    age: 27,
    bye: 5,
    rank: 16,
    posRank: 2,
    tier: 1,
    adp: 8.5,
    projPts: 415,
    vbd: 123,
    tradeValue: 85,
    injuryRisk: 'Medium',
    upside: 'Ceiling',
    status: 'Active',
    notes: 'Dual-threat stud. Rushing TDs make floor incredibly high. Week 5 bye is early — manageable.',
    snapPct: 100,
    scheduleRating: 6,
    playoffRating: 7,
  },
  {
    id: 'lamar-jackson',
    name: 'Lamar Jackson',
    team: 'BAL',
    position: 'QB',
    age: 28,
    bye: 7,
    rank: 22,
    posRank: 3,
    tier: 1,
    adp: 12.0,
    projPts: 402,
    vbd: 110,
    tradeValue: 80,
    injuryRisk: 'Medium',
    upside: 'Ceiling',
    status: 'Active',
    notes: 'Back-to-back MVP winner. Rushing floor is unmatched. Slight injury concern from running style.',
    snapPct: 100,
    scheduleRating: 5,
    playoffRating: 6,
  },
  {
    id: 'jayden-daniels',
    name: 'Jayden Daniels',
    team: 'WAS',
    position: 'QB',
    age: 24,
    bye: 11,
    rank: 38,
    posRank: 4,
    tier: 2,
    adp: 22.0,
    projPts: 382,
    vbd: 90,
    tradeValue: 73,
    injuryRisk: 'Medium',
    upside: 'High',
    status: 'Active',
    notes: 'Explosive sophomore QB. Rushes for huge numbers. Week 11 bye pairs well with other late-bye players.',
    snapPct: 100,
    scheduleRating: 7,
    playoffRating: 8,
  },
  {
    id: 'patrick-mahomes',
    name: 'Patrick Mahomes',
    team: 'KC',
    position: 'QB',
    age: 29,
    bye: 11,
    rank: 42,
    posRank: 5,
    tier: 2,
    adp: 28.0,
    projPts: 378,
    vbd: 86,
    tradeValue: 70,
    injuryRisk: 'Low',
    upside: 'High',
    status: 'Active',
    notes: 'Safe floor every week. TD machine but lacks rushing upside of top-3 QBs. Best QB1 for risk-averse managers.',
    snapPct: 100,
    scheduleRating: 5,
    playoffRating: 6,
  },
  {
    id: 'cj-stroud',
    name: 'C.J. Stroud',
    team: 'HOU',
    position: 'QB',
    age: 23,
    bye: 8,
    rank: 58,
    posRank: 6,
    tier: 2,
    adp: 46.0,
    projPts: 358,
    vbd: 66,
    tradeValue: 60,
    injuryRisk: 'Low',
    upside: 'High',
    status: 'Active',
    notes: 'Elite arm talent. Tank Dell and Nico Collins give him weapons. Late-round QB value.',
    snapPct: 100,
    scheduleRating: 6,
    playoffRating: 7,
  },
  {
    id: 'brock-purdy',
    name: 'Brock Purdy',
    team: 'SF',
    position: 'QB',
    age: 25,
    bye: 5,
    rank: 65,
    posRank: 7,
    tier: 2,
    adp: 58.0,
    projPts: 348,
    vbd: 56,
    tradeValue: 54,
    injuryRisk: 'Low',
    upside: 'Medium',
    status: 'Active',
    notes: 'System QB with elite efficiency. McCaffrey dependency is a risk but offense is loaded.',
    snapPct: 100,
    scheduleRating: 5,
    playoffRating: 5,
  },
  {
    id: 'jordan-love',
    name: 'Jordan Love',
    team: 'GB',
    position: 'QB',
    age: 26,
    bye: 8,
    rank: 80,
    posRank: 8,
    tier: 3,
    adp: 76.0,
    projPts: 332,
    vbd: 40,
    tradeValue: 44,
    injuryRisk: 'Low',
    upside: 'High',
    status: 'Active',
    notes: 'Ascending QB2. Malik Willis is a viable handcuff. Throw-heavy offense benefits his value.',
    snapPct: 100,
    scheduleRating: 7,
    playoffRating: 8,
  },
  {
    id: 'sam-darnold',
    name: 'Sam Darnold',
    team: 'MIN',
    position: 'QB',
    age: 28,
    bye: 5,
    rank: 88,
    posRank: 9,
    tier: 3,
    adp: 88.0,
    projPts: 325,
    vbd: 33,
    tradeValue: 38,
    injuryRisk: 'Medium',
    upside: 'Medium',
    status: 'Active',
    notes: 'Justin Jefferson makes him viable. Streaming upside but volatile.',
    snapPct: 100,
    scheduleRating: 6,
    playoffRating: 6,
  },
  {
    id: 'dak-prescott',
    name: 'Dak Prescott',
    team: 'DAL',
    position: 'QB',
    age: 31,
    bye: 7,
    rank: 95,
    posRank: 10,
    tier: 3,
    adp: 96.0,
    projPts: 318,
    vbd: 26,
    tradeValue: 32,
    injuryRisk: 'Medium',
    upside: 'Medium',
    status: 'Active',
    notes: 'CeeDee Lamb lifts his floor. Good bye week pairing with other Wk7 teams.',
    snapPct: 100,
    scheduleRating: 6,
    playoffRating: 7,
  },
  {
    id: 'tua-tagovailoa',
    name: 'Tua Tagovailoa',
    team: 'MIA',
    position: 'QB',
    age: 27,
    bye: 11,
    rank: 102,
    posRank: 11,
    tier: 3,
    adp: 108.0,
    projPts: 310,
    vbd: 18,
    tradeValue: 26,
    injuryRisk: 'High',
    upside: 'Medium',
    status: 'Active',
    notes: 'Concussion history is a major concern. Elite when healthy with Hill & Waddle.',
    snapPct: 100,
    scheduleRating: 6,
    playoffRating: 7,
  },
  {
    id: 'bo-nix',
    name: 'Bo Nix',
    team: 'DEN',
    position: 'QB',
    age: 24,
    bye: 11,
    rank: 112,
    posRank: 12,
    tier: 3,
    adp: 118.0,
    projPts: 298,
    vbd: 6,
    tradeValue: 18,
    injuryRisk: 'Low',
    upside: 'High',
    status: 'Active',
    notes: 'Improving sophomore. Courtland Sutton is his WR1. Upside pick in late rounds.',
    snapPct: 100,
    scheduleRating: 7,
    playoffRating: 7,
  },
  {
    id: 'anthony-richardson',
    name: 'Anthony Richardson',
    team: 'IND',
    position: 'QB',
    age: 23,
    bye: 10,
    rank: 128,
    posRank: 13,
    tier: 4,
    adp: 132.0,
    projPts: 292,
    vbd: 0,
    tradeValue: 12,
    injuryRisk: 'High',
    upside: 'Ceiling',
    status: 'Active',
    notes: 'Insane rushing upside but injury-prone. Massive ceiling if he stays healthy.',
    snapPct: 100,
    scheduleRating: 7,
    playoffRating: 7,
  },
  {
    id: 'baker-mayfield',
    name: 'Baker Mayfield',
    team: 'TB',
    position: 'QB',
    age: 30,
    bye: 10,
    rank: 145,
    posRank: 14,
    tier: 4,
    adp: 148.0,
    projPts: 278,
    vbd: 0,
    tradeValue: 8,
    injuryRisk: 'Low',
    upside: 'Medium',
    status: 'Active',
    notes: 'Mike Evans keeps him relevant. Decent streaming option in Week 10 bye weeks.',
    snapPct: 100,
    scheduleRating: 6,
    playoffRating: 6,
  },
  {
    id: 'kirk-cousins',
    name: 'Kirk Cousins',
    team: 'ATL',
    position: 'QB',
    age: 36,
    bye: 6,
    rank: 158,
    posRank: 15,
    tier: 5,
    adp: 170.0,
    projPts: 268,
    vbd: 0,
    tradeValue: 5,
    injuryRisk: 'Medium',
    upside: 'Low',
    status: 'Active',
    notes: 'Bijan Robinson and Drake London help. Aging but consistent enough as a streamer.',
    snapPct: 100,
    scheduleRating: 6,
    playoffRating: 5,
  },

  // ─── RUNNING BACKS ────────────────────────────────────────────────
  {
    id: 'saquon-barkley',
    name: 'Saquon Barkley',
    team: 'PHI',
    position: 'RB',
    age: 28,
    bye: 5,
    rank: 2,
    posRank: 1,
    tier: 1,
    adp: 1.5,
    projPts: 372,
    vbd: 280,
    tradeValue: 100,
    injuryRisk: 'Medium',
    upside: 'Ceiling',
    status: 'Active',
    notes: 'Legitimate 2,000-yard threat. Eagles use him in passing game too. Consistent RB1 monster.',
    rushShare: 75,
    snapPct: 85,
    scheduleRating: 6,
    playoffRating: 7,
  },
  {
    id: 'christian-mccaffrey',
    name: 'Christian McCaffrey',
    team: 'SF',
    position: 'RB',
    age: 28,
    bye: 5,
    rank: 3,
    posRank: 2,
    tier: 1,
    adp: 2.2,
    projPts: 368,
    vbd: 276,
    tradeValue: 98,
    injuryRisk: 'High',
    upside: 'Ceiling',
    status: 'Active',
    notes: 'Best player in fantasy when healthy. Injury history is the only concern. Purdy is his handcuff.',
    rushShare: 72,
    snapPct: 88,
    scheduleRating: 5,
    playoffRating: 5,
  },
  {
    id: 'derrick-henry',
    name: 'Derrick Henry',
    team: 'BAL',
    position: 'RB',
    age: 31,
    bye: 7,
    rank: 5,
    posRank: 3,
    tier: 1,
    adp: 3.8,
    projPts: 352,
    vbd: 260,
    tradeValue: 95,
    injuryRisk: 'Low',
    upside: 'Ceiling',
    status: 'Active',
    notes: 'Age-defying iron man. Lamar Jackson opens massive run lanes. Has never had a significant injury.',
    rushShare: 80,
    snapPct: 80,
    scheduleRating: 5,
    playoffRating: 6,
  },
  {
    id: 'jahmyr-gibbs',
    name: 'Jahmyr Gibbs',
    team: 'DET',
    position: 'RB',
    age: 22,
    bye: 6,
    rank: 8,
    posRank: 4,
    tier: 1,
    adp: 5.5,
    projPts: 315,
    vbd: 223,
    tradeValue: 88,
    injuryRisk: 'Low',
    upside: 'Ceiling',
    status: 'Active',
    notes: 'Young lightning bolt. Shares with Montgomery but gets the speed-game work and passing downs. Elite upside.',
    rushShare: 55,
    snapPct: 75,
    scheduleRating: 6,
    playoffRating: 7,
  },
  {
    id: 'devon-achane',
    name: "De'Von Achane",
    team: 'MIA',
    position: 'RB',
    age: 23,
    bye: 11,
    rank: 11,
    posRank: 5,
    tier: 1,
    adp: 7.5,
    projPts: 298,
    vbd: 206,
    tradeValue: 83,
    injuryRisk: 'Medium',
    upside: 'Ceiling',
    status: 'Active',
    notes: 'Fastest player in NFL. Huge ceiling but Tua injury risk flows down. Explosive plays every week.',
    rushShare: 65,
    snapPct: 72,
    scheduleRating: 6,
    playoffRating: 7,
  },
  {
    id: 'bijan-robinson',
    name: 'Bijan Robinson',
    team: 'ATL',
    position: 'RB',
    age: 23,
    bye: 6,
    rank: 18,
    posRank: 6,
    tier: 1,
    adp: 9.2,
    projPts: 288,
    vbd: 196,
    tradeValue: 78,
    injuryRisk: 'Low',
    upside: 'High',
    status: 'Active',
    notes: 'True workhorse RB. Three-down back with receiving upside. Cousins to Bijan is a high-volume connection.',
    rushShare: 72,
    snapPct: 82,
    scheduleRating: 7,
    playoffRating: 6,
  },
  {
    id: 'breece-hall',
    name: 'Breece Hall',
    team: 'NYJ',
    position: 'RB',
    age: 23,
    bye: 8,
    rank: 24,
    posRank: 7,
    tier: 2,
    adp: 12.0,
    projPts: 280,
    vbd: 188,
    tradeValue: 74,
    injuryRisk: 'Medium',
    upside: 'High',
    status: 'Active',
    notes: 'Workhorse back in new-look Jets offense. Route runner with elite receiving ability in PPR.',
    rushShare: 70,
    snapPct: 80,
    scheduleRating: 6,
    playoffRating: 6,
  },
  {
    id: 'josh-jacobs',
    name: 'Josh Jacobs',
    team: 'GB',
    position: 'RB',
    age: 26,
    bye: 8,
    rank: 30,
    posRank: 8,
    tier: 2,
    adp: 18.5,
    projPts: 268,
    vbd: 176,
    tradeValue: 68,
    injuryRisk: 'Low',
    upside: 'High',
    status: 'Active',
    notes: 'Jordan Love connection in passing game is underrated. Workhorse with elite floor.',
    rushShare: 68,
    snapPct: 78,
    scheduleRating: 7,
    playoffRating: 8,
  },
  {
    id: 'james-cook',
    name: 'James Cook',
    team: 'BUF',
    position: 'RB',
    age: 24,
    bye: 7,
    rank: 35,
    posRank: 9,
    tier: 2,
    adp: 22.5,
    projPts: 255,
    vbd: 163,
    tradeValue: 62,
    injuryRisk: 'Low',
    upside: 'High',
    status: 'Active',
    notes: 'Big-play back for Josh Allen. Benefits from elite offense around him. High ceiling games weekly.',
    rushShare: 62,
    snapPct: 72,
    scheduleRating: 7,
    playoffRating: 8,
  },
  {
    id: 'isiah-pacheco',
    name: 'Isiah Pacheco',
    team: 'KC',
    position: 'RB',
    age: 25,
    bye: 11,
    rank: 42,
    posRank: 10,
    tier: 2,
    adp: 32.0,
    projPts: 242,
    vbd: 150,
    tradeValue: 56,
    injuryRisk: 'Medium',
    upside: 'High',
    status: 'Active',
    notes: 'TD vulture in best offense in football. Mahomes TD totals flow down. Safe RB2 floor.',
    rushShare: 65,
    snapPct: 74,
    scheduleRating: 5,
    playoffRating: 5,
  },
  {
    id: 'kyren-williams',
    name: 'Kyren Williams',
    team: 'LAR',
    position: 'RB',
    age: 24,
    bye: 10,
    rank: 48,
    posRank: 11,
    tier: 2,
    adp: 38.0,
    projPts: 238,
    vbd: 146,
    tradeValue: 52,
    injuryRisk: 'Medium',
    upside: 'High',
    status: 'Active',
    notes: 'Bell-cow back for McVay offense. Solid receiving work. Stafford-led offense gives him a high floor.',
    rushShare: 70,
    snapPct: 76,
    scheduleRating: 6,
    playoffRating: 6,
  },
  {
    id: 'jonathan-taylor',
    name: 'Jonathan Taylor',
    team: 'IND',
    position: 'RB',
    age: 25,
    bye: 10,
    rank: 52,
    posRank: 12,
    tier: 2,
    adp: 45.0,
    projPts: 228,
    vbd: 136,
    tradeValue: 48,
    injuryRisk: 'High',
    upside: 'High',
    status: 'Active',
    notes: 'Elite talent but ankle concerns limit him. When healthy, top-5 RB upside. QB situation murky.',
    rushShare: 68,
    snapPct: 72,
    scheduleRating: 7,
    playoffRating: 7,
  },
  {
    id: 'joe-mixon',
    name: 'Joe Mixon',
    team: 'HOU',
    position: 'RB',
    age: 28,
    bye: 8,
    rank: 60,
    posRank: 13,
    tier: 3,
    adp: 52.0,
    projPts: 218,
    vbd: 126,
    tradeValue: 44,
    injuryRisk: 'Medium',
    upside: 'High',
    status: 'Active',
    notes: 'CJ Stroud offense is explosive. Great for TDs. Consistent three-down usage.',
    rushShare: 66,
    snapPct: 74,
    scheduleRating: 6,
    playoffRating: 7,
  },
  {
    id: 'rhamondre-stevenson',
    name: 'Rhamondre Stevenson',
    team: 'NE',
    position: 'RB',
    age: 26,
    bye: 12,
    rank: 68,
    posRank: 14,
    tier: 3,
    adp: 62.0,
    projPts: 208,
    vbd: 116,
    tradeValue: 38,
    injuryRisk: 'Low',
    upside: 'Medium',
    status: 'Active',
    notes: 'New Patriots offense could unlock him. Safe workhorse but QB situation limits upside.',
    rushShare: 64,
    snapPct: 70,
    scheduleRating: 7,
    playoffRating: 7,
  },
  {
    id: 'travis-etienne',
    name: 'Travis Etienne',
    team: 'JAC',
    position: 'RB',
    age: 25,
    bye: 9,
    rank: 74,
    posRank: 15,
    tier: 3,
    adp: 70.0,
    projPts: 200,
    vbd: 108,
    tradeValue: 34,
    injuryRisk: 'Medium',
    upside: 'Medium',
    status: 'Active',
    notes: 'Volume carrier but Jacksonville offense is limited. Can be a consistent RB2.',
    rushShare: 62,
    snapPct: 72,
    scheduleRating: 8,
    playoffRating: 8,
  },
  {
    id: 'tony-pollard',
    name: 'Tony Pollard',
    team: 'TEN',
    position: 'RB',
    age: 27,
    bye: 5,
    rank: 80,
    posRank: 16,
    tier: 3,
    adp: 78.0,
    projPts: 195,
    vbd: 103,
    tradeValue: 30,
    injuryRisk: 'Low',
    upside: 'Medium',
    status: 'Active',
    notes: 'Workhorse in Tennessee but weak offense limits ceiling. Safe RB2/flex.',
    rushShare: 65,
    snapPct: 75,
    scheduleRating: 8,
    playoffRating: 8,
  },
  {
    id: 'david-montgomery',
    name: 'David Montgomery',
    team: 'DET',
    position: 'RB',
    age: 27,
    bye: 6,
    rank: 85,
    posRank: 17,
    tier: 3,
    adp: 85.0,
    projPts: 188,
    vbd: 96,
    tradeValue: 27,
    injuryRisk: 'Low',
    upside: 'Medium',
    status: 'Active',
    notes: 'TD vulture in Detroit. Great team, gets red-zone work over Gibbs. RB2 in good situations.',
    rushShare: 45,
    snapPct: 65,
    scheduleRating: 6,
    playoffRating: 7,
  },
  {
    id: 'aaron-jones',
    name: 'Aaron Jones',
    team: 'MIN',
    position: 'RB',
    age: 30,
    bye: 5,
    rank: 90,
    posRank: 18,
    tier: 3,
    adp: 92.0,
    projPts: 182,
    vbd: 90,
    tradeValue: 24,
    injuryRisk: 'Medium',
    upside: 'Medium',
    status: 'Active',
    notes: 'Justin Jefferson opens running lanes. Age concern but still capable. Receiving upside in PPR.',
    rushShare: 58,
    snapPct: 68,
    scheduleRating: 6,
    playoffRating: 6,
  },
  {
    id: 'zach-charbonnet',
    name: 'Zach Charbonnet',
    team: 'SEA',
    position: 'RB',
    age: 24,
    bye: 9,
    rank: 96,
    posRank: 19,
    tier: 3,
    adp: 98.0,
    projPts: 175,
    vbd: 83,
    tradeValue: 21,
    injuryRisk: 'Low',
    upside: 'High',
    status: 'Active',
    notes: 'Kenneth Walker handcuff/competitor. If Walker misses time, becomes instant RB1. Great sleeper.',
    rushShare: 40,
    snapPct: 55,
    scheduleRating: 7,
    playoffRating: 7,
  },
  {
    id: 'rachaad-white',
    name: 'Rachaad White',
    team: 'TB',
    position: 'RB',
    age: 25,
    bye: 10,
    rank: 102,
    posRank: 20,
    tier: 3,
    adp: 105.0,
    projPts: 170,
    vbd: 78,
    tradeValue: 18,
    injuryRisk: 'Low',
    upside: 'Medium',
    status: 'Active',
    notes: 'Receiving back for Baker Mayfield. Consistent PPR producer. Solid RB2/flex floor.',
    rushShare: 55,
    snapPct: 70,
    scheduleRating: 6,
    playoffRating: 6,
  },
  {
    id: 'javonte-williams',
    name: 'Javonte Williams',
    team: 'DEN',
    position: 'RB',
    age: 24,
    bye: 11,
    rank: 108,
    posRank: 21,
    tier: 4,
    adp: 112.0,
    projPts: 162,
    vbd: 70,
    tradeValue: 15,
    injuryRisk: 'Medium',
    upside: 'High',
    status: 'Active',
    notes: 'Recovering from 2022 knee injury. Still has elite talent. Bo Nix offense is improving.',
    rushShare: 55,
    snapPct: 65,
    scheduleRating: 7,
    playoffRating: 7,
  },
  {
    id: 'najee-harris',
    name: 'Najee Harris',
    team: 'PIT',
    position: 'RB',
    age: 27,
    bye: 9,
    rank: 115,
    posRank: 22,
    tier: 4,
    adp: 120.0,
    projPts: 158,
    vbd: 66,
    tradeValue: 13,
    injuryRisk: 'Low',
    upside: 'Medium',
    status: 'Active',
    notes: 'Volume workhorse in Pittsburgh. Weak offense limits upside but near 1,000 yards is the floor.',
    rushShare: 62,
    snapPct: 72,
    scheduleRating: 5,
    playoffRating: 5,
  },
  {
    id: 'chuba-hubbard',
    name: 'Chuba Hubbard',
    team: 'CAR',
    position: 'RB',
    age: 25,
    bye: 10,
    rank: 122,
    posRank: 23,
    tier: 4,
    adp: 128.0,
    projPts: 152,
    vbd: 60,
    tradeValue: 11,
    injuryRisk: 'Low',
    upside: 'Medium',
    status: 'Active',
    notes: 'Carolina workhorse. Weak team means lots of carries in catch-up situations.',
    rushShare: 60,
    snapPct: 70,
    scheduleRating: 8,
    playoffRating: 8,
  },
  {
    id: 'tyjae-spears',
    name: 'Tyjae Spears',
    team: 'TEN',
    position: 'RB',
    age: 23,
    bye: 5,
    rank: 130,
    posRank: 24,
    tier: 4,
    adp: 135.0,
    projPts: 148,
    vbd: 56,
    tradeValue: 10,
    injuryRisk: 'Low',
    upside: 'High',
    status: 'Active',
    notes: 'Tony Pollard handcuff with serious receiving ability. Could be 40-catch back if featured.',
    rushShare: 35,
    snapPct: 50,
    scheduleRating: 8,
    playoffRating: 8,
  },
  {
    id: 'dandre-swift',
    name: "D'Andre Swift",
    team: 'CHI',
    position: 'RB',
    age: 25,
    bye: 9,
    rank: 136,
    posRank: 25,
    tier: 4,
    adp: 142.0,
    projPts: 142,
    vbd: 50,
    tradeValue: 9,
    injuryRisk: 'High',
    upside: 'High',
    status: 'Active',
    notes: 'Injury-prone but electrifying talent. Caleb Williams upside. Big play potential weekly.',
    rushShare: 55,
    snapPct: 65,
    scheduleRating: 7,
    playoffRating: 7,
  },
  {
    id: 'gus-edwards',
    name: 'Gus Edwards',
    team: 'LAC',
    position: 'RB',
    age: 29,
    bye: 6,
    rank: 148,
    posRank: 26,
    tier: 4,
    adp: 155.0,
    projPts: 128,
    vbd: 36,
    tradeValue: 7,
    injuryRisk: 'Medium',
    upside: 'Medium',
    status: 'Active',
    notes: 'Red-zone vulture. Gets TDs near the goal line. Solid handcuff/flex option.',
    rushShare: 45,
    snapPct: 55,
    scheduleRating: 6,
    playoffRating: 6,
  },
  {
    id: 'jerome-ford',
    name: 'Jerome Ford',
    team: 'CLE',
    position: 'RB',
    age: 25,
    bye: 10,
    rank: 152,
    posRank: 27,
    tier: 5,
    adp: 160.0,
    projPts: 118,
    vbd: 26,
    tradeValue: 6,
    injuryRisk: 'Low',
    upside: 'Medium',
    status: 'Active',
    notes: 'Will be RB1 if Nick Chubb/Hill get hurt. Good handcuff/streaming option.',
    rushShare: 40,
    snapPct: 55,
    scheduleRating: 7,
    playoffRating: 7,
  },
  {
    id: 'kareem-hunt',
    name: 'Kareem Hunt',
    team: 'FA',
    position: 'RB',
    age: 29,
    bye: 0,
    rank: 160,
    posRank: 28,
    tier: 5,
    adp: 172.0,
    projPts: 108,
    vbd: 16,
    tradeValue: 5,
    injuryRisk: 'Low',
    upside: 'Medium',
    status: 'Active',
    notes: 'Veteran who can contribute wherever he lands. Monitor for signing before drafting.',
    rushShare: 35,
    snapPct: 50,
    scheduleRating: 6,
    playoffRating: 6,
  },

  // ─── WIDE RECEIVERS ────────────────────────────────────────────────
  {
    id: 'justin-jefferson',
    name: 'Justin Jefferson',
    team: 'MIN',
    position: 'WR',
    age: 25,
    bye: 5,
    rank: 1,
    posRank: 1,
    tier: 1,
    adp: 1.2,
    projPts: 378,
    vbd: 268,
    tradeValue: 100,
    injuryRisk: 'Low',
    upside: 'Ceiling',
    status: 'Active',
    notes: 'Best WR in NFL. Elite route runner, yards after catch, contested catches. The clear overall WR1.',
    targetShare: 30,
    snapPct: 92,
    scheduleRating: 6,
    playoffRating: 6,
  },
  {
    id: 'jamarr-chase',
    name: "Ja'Marr Chase",
    team: 'CIN',
    position: 'WR',
    age: 25,
    bye: 7,
    rank: 4,
    posRank: 2,
    tier: 1,
    adp: 2.5,
    projPts: 368,
    vbd: 258,
    tradeValue: 97,
    injuryRisk: 'Low',
    upside: 'Ceiling',
    status: 'Active',
    notes: 'Signed mega-deal and is a Bengals cornerstone. Burrow connection is elite. Signed through 2030.',
    targetShare: 29,
    snapPct: 90,
    scheduleRating: 6,
    playoffRating: 7,
  },
  {
    id: 'ceedee-lamb',
    name: 'CeeDee Lamb',
    team: 'DAL',
    position: 'WR',
    age: 25,
    bye: 7,
    rank: 6,
    posRank: 3,
    tier: 1,
    adp: 4.2,
    projPts: 358,
    vbd: 248,
    tradeValue: 94,
    injuryRisk: 'Low',
    upside: 'Ceiling',
    status: 'Active',
    notes: 'Route running genius. 30%+ target share. Dak connection is elite. WR1 every week when healthy.',
    targetShare: 32,
    snapPct: 93,
    scheduleRating: 6,
    playoffRating: 7,
  },
  {
    id: 'tyreek-hill',
    name: 'Tyreek Hill',
    team: 'MIA',
    position: 'WR',
    age: 31,
    bye: 11,
    rank: 9,
    posRank: 4,
    tier: 1,
    adp: 6.5,
    projPts: 342,
    vbd: 232,
    tradeValue: 88,
    injuryRisk: 'Low',
    upside: 'Ceiling',
    status: 'Active',
    notes: 'Still fastest WR alive. Tua health is the concern but ceiling is 200 targets. Elite PPR producer.',
    targetShare: 28,
    snapPct: 90,
    scheduleRating: 6,
    playoffRating: 7,
  },
  {
    id: 'amon-ra-st-brown',
    name: 'Amon-Ra St. Brown',
    team: 'DET',
    position: 'WR',
    age: 25,
    bye: 6,
    rank: 13,
    posRank: 5,
    tier: 1,
    adp: 8.8,
    projPts: 322,
    vbd: 212,
    tradeValue: 83,
    injuryRisk: 'Low',
    upside: 'High',
    status: 'Active',
    notes: 'PPR monster. 160+ targets annually. Short routes make him volume king in Jared Goff system.',
    targetShare: 26,
    snapPct: 89,
    scheduleRating: 6,
    playoffRating: 7,
  },
  {
    id: 'aj-brown',
    name: 'A.J. Brown',
    team: 'PHI',
    position: 'WR',
    age: 27,
    bye: 5,
    rank: 17,
    posRank: 6,
    tier: 1,
    adp: 10.5,
    projPts: 308,
    vbd: 198,
    tradeValue: 77,
    injuryRisk: 'Medium',
    upside: 'High',
    status: 'Active',
    notes: 'Physically dominant WR. Big-play machine with elite YAC. Injury history is only knock on him.',
    targetShare: 25,
    snapPct: 87,
    scheduleRating: 6,
    playoffRating: 7,
  },
  {
    id: 'puka-nacua',
    name: 'Puka Nacua',
    team: 'LAR',
    position: 'WR',
    age: 23,
    bye: 10,
    rank: 25,
    posRank: 7,
    tier: 2,
    adp: 15.0,
    projPts: 292,
    vbd: 182,
    tradeValue: 71,
    injuryRisk: 'Low',
    upside: 'High',
    status: 'Active',
    notes: 'Route running wizard. Cooper Kupp departure makes him the clear WR1. Stafford loves him.',
    targetShare: 24,
    snapPct: 88,
    scheduleRating: 6,
    playoffRating: 6,
  },
  {
    id: 'drake-london',
    name: 'Drake London',
    team: 'ATL',
    position: 'WR',
    age: 23,
    bye: 6,
    rank: 29,
    posRank: 8,
    tier: 2,
    adp: 19.0,
    projPts: 282,
    vbd: 172,
    tradeValue: 66,
    injuryRisk: 'Low',
    upside: 'High',
    status: 'Active',
    notes: 'Big body WR with elite athletic traits. Kirk Cousins-to-London is a major upgrade from 2024.',
    targetShare: 23,
    snapPct: 86,
    scheduleRating: 7,
    playoffRating: 6,
  },
  {
    id: 'mike-evans',
    name: 'Mike Evans',
    team: 'TB',
    position: 'WR',
    age: 31,
    bye: 10,
    rank: 36,
    posRank: 9,
    tier: 2,
    adp: 24.0,
    projPts: 268,
    vbd: 158,
    tradeValue: 60,
    injuryRisk: 'Low',
    upside: 'High',
    status: 'Active',
    notes: 'Ageless TD machine. 11 consecutive 1,000-yard seasons. Red-zone monster.',
    targetShare: 22,
    snapPct: 85,
    scheduleRating: 6,
    playoffRating: 6,
  },
  {
    id: 'dk-metcalf',
    name: 'DK Metcalf',
    team: 'SEA',
    position: 'WR',
    age: 27,
    bye: 9,
    rank: 43,
    posRank: 10,
    tier: 2,
    adp: 30.0,
    projPts: 258,
    vbd: 148,
    tradeValue: 55,
    injuryRisk: 'Low',
    upside: 'High',
    status: 'Active',
    notes: 'Freak athlete. New QB elevates his value. 10+ TD upside every season.',
    targetShare: 23,
    snapPct: 87,
    scheduleRating: 7,
    playoffRating: 7,
  },
  {
    id: 'keenan-allen',
    name: 'Keenan Allen',
    team: 'CHI',
    position: 'WR',
    age: 32,
    bye: 9,
    rank: 49,
    posRank: 11,
    tier: 2,
    adp: 38.0,
    projPts: 248,
    vbd: 138,
    tradeValue: 50,
    injuryRisk: 'Medium',
    upside: 'High',
    status: 'Active',
    notes: 'Caleb Williams chemistry is building. Route running vet keeps him elite. Age and injury risk are concerns.',
    targetShare: 22,
    snapPct: 84,
    scheduleRating: 7,
    playoffRating: 7,
  },
  {
    id: 'devonta-smith',
    name: 'DeVonta Smith',
    team: 'PHI',
    position: 'WR',
    age: 28,
    bye: 5,
    rank: 53,
    posRank: 12,
    tier: 2,
    adp: 42.0,
    projPts: 242,
    vbd: 132,
    tradeValue: 47,
    injuryRisk: 'Low',
    upside: 'High',
    status: 'Active',
    notes: 'Elite route runner in elite offense. Teams at WR1 upside when AJ Brown misses games.',
    targetShare: 21,
    snapPct: 85,
    scheduleRating: 6,
    playoffRating: 7,
  },
  {
    id: 'tee-higgins',
    name: 'Tee Higgins',
    team: 'CIN',
    position: 'WR',
    age: 25,
    bye: 7,
    rank: 57,
    posRank: 13,
    tier: 2,
    adp: 48.0,
    projPts: 235,
    vbd: 125,
    tradeValue: 44,
    injuryRisk: 'Medium',
    upside: 'High',
    status: 'Active',
    notes: 'In Burrow offense with Chase. Averages 14+ yards per catch when healthy. Elite upside.',
    targetShare: 19,
    snapPct: 82,
    scheduleRating: 6,
    playoffRating: 7,
  },
  {
    id: 'brandon-aiyuk',
    name: 'Brandon Aiyuk',
    team: 'SF',
    position: 'WR',
    age: 27,
    bye: 5,
    rank: 61,
    posRank: 14,
    tier: 2,
    adp: 55.0,
    projPts: 228,
    vbd: 118,
    tradeValue: 41,
    injuryRisk: 'Low',
    upside: 'High',
    status: 'Active',
    notes: 'Elite speed-route runner in Shanahan system. MCM health determines how many targets he sees.',
    targetShare: 20,
    snapPct: 83,
    scheduleRating: 5,
    playoffRating: 5,
  },
  {
    id: 'garrett-wilson',
    name: 'Garrett Wilson',
    team: 'NYJ',
    position: 'WR',
    age: 24,
    bye: 8,
    rank: 66,
    posRank: 15,
    tier: 3,
    adp: 62.0,
    projPts: 222,
    vbd: 112,
    tradeValue: 38,
    injuryRisk: 'Low',
    upside: 'High',
    status: 'Active',
    notes: 'Elite route runner wasting in inconsistent offense. New QB could unlock massive upside.',
    targetShare: 22,
    snapPct: 88,
    scheduleRating: 6,
    playoffRating: 6,
  },
  {
    id: 'chris-olave',
    name: 'Chris Olave',
    team: 'NO',
    position: 'WR',
    age: 24,
    bye: 6,
    rank: 69,
    posRank: 16,
    tier: 3,
    adp: 68.0,
    projPts: 218,
    vbd: 108,
    tradeValue: 36,
    injuryRisk: 'Medium',
    upside: 'High',
    status: 'Active',
    notes: 'Elite speed with great route running. New QB needed. When healthy, top-20 WR easily.',
    targetShare: 21,
    snapPct: 85,
    scheduleRating: 7,
    playoffRating: 7,
  },
  {
    id: 'terry-mclaurin',
    name: 'Terry McLaurin',
    team: 'WAS',
    position: 'WR',
    age: 29,
    bye: 11,
    rank: 73,
    posRank: 17,
    tier: 3,
    adp: 74.0,
    projPts: 212,
    vbd: 102,
    tradeValue: 33,
    injuryRisk: 'Low',
    upside: 'High',
    status: 'Active',
    notes: 'Jayden Daniels unleashes him. Best year of his career incoming with real QB play.',
    targetShare: 22,
    snapPct: 87,
    scheduleRating: 7,
    playoffRating: 8,
  },
  {
    id: 'jaylen-waddle',
    name: 'Jaylen Waddle',
    team: 'MIA',
    position: 'WR',
    age: 26,
    bye: 11,
    rank: 76,
    posRank: 18,
    tier: 3,
    adp: 80.0,
    projPts: 205,
    vbd: 95,
    tradeValue: 30,
    injuryRisk: 'Medium',
    upside: 'High',
    status: 'Active',
    notes: 'Elite speed alongside Hill. Tua health is the key. Can post WR1 games when Hill is out.',
    targetShare: 19,
    snapPct: 83,
    scheduleRating: 6,
    playoffRating: 7,
  },
  {
    id: 'calvin-ridley',
    name: 'Calvin Ridley',
    team: 'TEN',
    position: 'WR',
    age: 30,
    bye: 5,
    rank: 81,
    posRank: 19,
    tier: 3,
    adp: 86.0,
    projPts: 198,
    vbd: 88,
    tradeValue: 27,
    injuryRisk: 'Medium',
    upside: 'High',
    status: 'Active',
    notes: 'Clear WR1 in Tennessee. New QB situation limits upside but volume target share is high.',
    targetShare: 24,
    snapPct: 86,
    scheduleRating: 8,
    playoffRating: 8,
  },
  {
    id: 'jordan-addison',
    name: 'Jordan Addison',
    team: 'MIN',
    position: 'WR',
    age: 23,
    bye: 5,
    rank: 86,
    posRank: 20,
    tier: 3,
    adp: 92.0,
    projPts: 192,
    vbd: 82,
    tradeValue: 25,
    injuryRisk: 'Low',
    upside: 'High',
    status: 'Active',
    notes: 'JJ shadow means open coverage constantly. 2025 could be breakout year with increased role.',
    targetShare: 18,
    snapPct: 80,
    scheduleRating: 6,
    playoffRating: 6,
  },
  {
    id: 'george-pickens',
    name: 'George Pickens',
    team: 'PIT',
    position: 'WR',
    age: 23,
    bye: 9,
    rank: 91,
    posRank: 21,
    tier: 3,
    adp: 98.0,
    projPts: 185,
    vbd: 75,
    tradeValue: 22,
    injuryRisk: 'Low',
    upside: 'High',
    status: 'Active',
    notes: 'Freakish talent in a bad passing offense. New QB could unlock top-15 WR ceiling.',
    targetShare: 22,
    snapPct: 85,
    scheduleRating: 5,
    playoffRating: 5,
  },
  {
    id: 'christian-watson',
    name: 'Christian Watson',
    team: 'GB',
    position: 'WR',
    age: 25,
    bye: 8,
    rank: 96,
    posRank: 22,
    tier: 3,
    adp: 105.0,
    projPts: 178,
    vbd: 68,
    tradeValue: 19,
    injuryRisk: 'High',
    upside: 'High',
    status: 'Active',
    notes: 'Elite speed. Hamstring issues hurt him in 2024. If healthy, big-play machine for Jordan Love.',
    targetShare: 18,
    snapPct: 75,
    scheduleRating: 7,
    playoffRating: 8,
  },
  {
    id: 'marvin-harrison-jr',
    name: 'Marvin Harrison Jr.',
    team: 'ARI',
    position: 'WR',
    age: 22,
    bye: 8,
    rank: 100,
    posRank: 23,
    tier: 3,
    adp: 112.0,
    projPts: 172,
    vbd: 62,
    tradeValue: 17,
    injuryRisk: 'Low',
    upside: 'Ceiling',
    status: 'Active',
    notes: 'Generational talent in year 2. Kyler Murray-MHJ connection improving rapidly. Major upside.',
    targetShare: 22,
    snapPct: 85,
    scheduleRating: 7,
    playoffRating: 7,
  },
  {
    id: 'rome-odunze',
    name: 'Rome Odunze',
    team: 'CHI',
    position: 'WR',
    age: 22,
    bye: 9,
    rank: 106,
    posRank: 24,
    tier: 3,
    adp: 118.0,
    projPts: 165,
    vbd: 55,
    tradeValue: 15,
    injuryRisk: 'Low',
    upside: 'Ceiling',
    status: 'Active',
    notes: 'Caleb Williams best friend. Year 2 leap expected. Freakish athlete in best Bears offense in years.',
    targetShare: 18,
    snapPct: 80,
    scheduleRating: 7,
    playoffRating: 7,
  },
  {
    id: 'xavier-worthy',
    name: 'Xavier Worthy',
    team: 'KC',
    position: 'WR',
    age: 22,
    bye: 11,
    rank: 111,
    posRank: 25,
    tier: 4,
    adp: 125.0,
    projPts: 158,
    vbd: 48,
    tradeValue: 13,
    injuryRisk: 'Low',
    upside: 'High',
    status: 'Active',
    notes: 'Fastest player in 2024 draft. Mahomes loves his speed. Good TD upside in red zone.',
    targetShare: 17,
    snapPct: 75,
    scheduleRating: 5,
    playoffRating: 5,
  },
  {
    id: 'ladd-mcconkey',
    name: 'Ladd McConkey',
    team: 'LAC',
    position: 'WR',
    age: 23,
    bye: 6,
    rank: 116,
    posRank: 26,
    tier: 4,
    adp: 132.0,
    projPts: 153,
    vbd: 43,
    tradeValue: 11,
    injuryRisk: 'Low',
    upside: 'High',
    status: 'Active',
    notes: 'Undervalued slot weapon. Justin Herbert connection is elite. Potential breakout in 2025.',
    targetShare: 19,
    snapPct: 80,
    scheduleRating: 6,
    playoffRating: 6,
  },
  {
    id: 'rashee-rice',
    name: 'Rashee Rice',
    team: 'KC',
    position: 'WR',
    age: 24,
    bye: 11,
    rank: 121,
    posRank: 27,
    tier: 4,
    adp: 138.0,
    projPts: 148,
    vbd: 38,
    tradeValue: 9,
    injuryRisk: 'High',
    upside: 'High',
    status: 'Active',
    notes: 'ACL recovery. When healthy, Mahomes slot WR1. High risk/reward pick in mid-rounds.',
    targetShare: 18,
    snapPct: 75,
    scheduleRating: 5,
    playoffRating: 5,
  },
  {
    id: 'courtland-sutton',
    name: 'Courtland Sutton',
    team: 'DEN',
    position: 'WR',
    age: 29,
    bye: 11,
    rank: 126,
    posRank: 28,
    tier: 4,
    adp: 145.0,
    projPts: 142,
    vbd: 32,
    tradeValue: 8,
    injuryRisk: 'Low',
    upside: 'Medium',
    status: 'Active',
    notes: 'Bo Nix WR1. Consistent producer with new offense. Solid flex option.',
    targetShare: 22,
    snapPct: 82,
    scheduleRating: 7,
    playoffRating: 7,
  },
  {
    id: 'tank-dell',
    name: 'Tank Dell',
    team: 'HOU',
    position: 'WR',
    age: 24,
    bye: 8,
    rank: 131,
    posRank: 29,
    tier: 4,
    adp: 152.0,
    projPts: 138,
    vbd: 28,
    tradeValue: 7,
    injuryRisk: 'High',
    upside: 'High',
    status: 'Active',
    notes: 'Coming off broken leg. CJ Stroud loves him. Major value if he returns to pre-injury form.',
    targetShare: 18,
    snapPct: 72,
    scheduleRating: 6,
    playoffRating: 7,
  },
  {
    id: 'dj-moore',
    name: 'DJ Moore',
    team: 'CHI',
    position: 'WR',
    age: 27,
    bye: 9,
    rank: 135,
    posRank: 30,
    tier: 4,
    adp: 158.0,
    projPts: 133,
    vbd: 23,
    tradeValue: 7,
    injuryRisk: 'Low',
    upside: 'Medium',
    status: 'Active',
    notes: 'Split targets with Keenan Allen and Rome Odunze. Volume WR but less ceiling.',
    targetShare: 18,
    snapPct: 78,
    scheduleRating: 7,
    playoffRating: 7,
  },
  {
    id: 'terry-mclaurin-streamer',
    name: 'Stefon Diggs',
    team: 'NE',
    position: 'WR',
    age: 31,
    bye: 12,
    rank: 140,
    posRank: 31,
    tier: 4,
    adp: 165.0,
    projPts: 128,
    vbd: 18,
    tradeValue: 6,
    injuryRisk: 'Medium',
    upside: 'Medium',
    status: 'Active',
    notes: 'Still has elite route running skills. New England WR1 with weak QB situation.',
    targetShare: 21,
    snapPct: 80,
    scheduleRating: 7,
    playoffRating: 7,
  },
  {
    id: 'hollywood-brown',
    name: 'Hollywood Brown',
    team: 'PIT',
    position: 'WR',
    age: 28,
    bye: 9,
    rank: 146,
    posRank: 32,
    tier: 4,
    adp: 172.0,
    projPts: 122,
    vbd: 12,
    tradeValue: 5,
    injuryRisk: 'High',
    upside: 'Medium',
    status: 'Active',
    notes: 'Deep threat for Steelers. Injury risk is high but upside is solid in good offense.',
    targetShare: 17,
    snapPct: 72,
    scheduleRating: 5,
    playoffRating: 5,
  },

  // ─── TIGHT ENDS ────────────────────────────────────────────────
  {
    id: 'brock-bowers',
    name: 'Brock Bowers',
    team: 'LV',
    position: 'TE',
    age: 21,
    bye: 10,
    rank: 7,
    posRank: 1,
    tier: 1,
    adp: 5.2,
    projPts: 232,
    vbd: 114,
    tradeValue: 88,
    injuryRisk: 'Low',
    upside: 'Ceiling',
    status: 'Active',
    notes: 'Broke all TE receiving records as a rookie. 1,100+ yards in year 1. Year 2 even better expected.',
    targetShare: 28,
    snapPct: 88,
    scheduleRating: 7,
    playoffRating: 7,
  },
  {
    id: 'travis-kelce',
    name: 'Travis Kelce',
    team: 'KC',
    position: 'TE',
    age: 35,
    bye: 11,
    rank: 11,
    posRank: 2,
    tier: 1,
    adp: 7.8,
    projPts: 222,
    vbd: 104,
    tradeValue: 82,
    injuryRisk: 'Medium',
    upside: 'High',
    status: 'Active',
    notes: 'Age 35 but still elite. Mahomes chemistry is unmatched. Concern is declining target share at his age.',
    targetShare: 24,
    snapPct: 86,
    scheduleRating: 5,
    playoffRating: 5,
  },
  {
    id: 'sam-laporta',
    name: 'Sam LaPorta',
    team: 'DET',
    position: 'TE',
    age: 24,
    bye: 6,
    rank: 20,
    posRank: 3,
    tier: 2,
    adp: 11.8,
    projPts: 202,
    vbd: 84,
    tradeValue: 70,
    injuryRisk: 'Low',
    upside: 'High',
    status: 'Active',
    notes: 'Goff loves the TE position. Rising star in explosive Detroit offense. Year 2 breakout.',
    targetShare: 20,
    snapPct: 82,
    scheduleRating: 6,
    playoffRating: 7,
  },
  {
    id: 'trey-mcbride',
    name: 'Trey McBride',
    team: 'ARI',
    position: 'TE',
    age: 25,
    bye: 8,
    rank: 27,
    posRank: 4,
    tier: 2,
    adp: 16.5,
    projPts: 192,
    vbd: 74,
    tradeValue: 62,
    injuryRisk: 'Low',
    upside: 'High',
    status: 'Active',
    notes: 'Kyler Murray loves tight ends. Elite YAC ability with great receiving hands.',
    targetShare: 21,
    snapPct: 84,
    scheduleRating: 7,
    playoffRating: 7,
  },
  {
    id: 'mark-andrews',
    name: 'Mark Andrews',
    team: 'BAL',
    position: 'TE',
    age: 29,
    bye: 7,
    rank: 34,
    posRank: 5,
    tier: 2,
    adp: 23.0,
    projPts: 185,
    vbd: 67,
    tradeValue: 55,
    injuryRisk: 'High',
    upside: 'High',
    status: 'Active',
    notes: 'Lamar Jackson loves him but ankle injury 2024 was scary. Top-5 TE when healthy.',
    targetShare: 19,
    snapPct: 78,
    scheduleRating: 5,
    playoffRating: 6,
  },
  {
    id: 'tj-hockenson',
    name: 'T.J. Hockenson',
    team: 'MIN',
    position: 'TE',
    age: 27,
    bye: 5,
    rank: 45,
    posRank: 6,
    tier: 2,
    adp: 32.0,
    projPts: 175,
    vbd: 57,
    tradeValue: 46,
    injuryRisk: 'High',
    upside: 'High',
    status: 'Active',
    notes: 'Coming back from ACL. Elite pass catcher for Vikings. Justin Jefferson opens huge TE windows.',
    targetShare: 18,
    snapPct: 75,
    scheduleRating: 6,
    playoffRating: 6,
  },
  {
    id: 'dallas-goedert',
    name: 'Dallas Goedert',
    team: 'PHI',
    position: 'TE',
    age: 29,
    bye: 5,
    rank: 54,
    posRank: 7,
    tier: 3,
    adp: 45.0,
    projPts: 168,
    vbd: 50,
    tradeValue: 40,
    injuryRisk: 'High',
    upside: 'High',
    status: 'Active',
    notes: 'Elite TE talent but injury-prone. When healthy, top-5 TE upside in loaded Eagles offense.',
    targetShare: 17,
    snapPct: 76,
    scheduleRating: 6,
    playoffRating: 7,
  },
  {
    id: 'jake-ferguson',
    name: 'Jake Ferguson',
    team: 'DAL',
    position: 'TE',
    age: 25,
    bye: 7,
    rank: 64,
    posRank: 8,
    tier: 3,
    adp: 58.0,
    projPts: 158,
    vbd: 40,
    tradeValue: 32,
    injuryRisk: 'Low',
    upside: 'High',
    status: 'Active',
    notes: 'Dak Prescott loves targeting TEs. Consistent producer in high-powered Cowboys offense.',
    targetShare: 16,
    snapPct: 80,
    scheduleRating: 6,
    playoffRating: 7,
  },
  {
    id: 'david-njoku',
    name: 'David Njoku',
    team: 'CLE',
    position: 'TE',
    age: 28,
    bye: 10,
    rank: 76,
    posRank: 9,
    tier: 3,
    adp: 72.0,
    projPts: 148,
    vbd: 30,
    tradeValue: 22,
    injuryRisk: 'Medium',
    upside: 'Medium',
    status: 'Active',
    notes: 'Quality TE but QB situation limits upside. Consistent target share is his best trait.',
    targetShare: 18,
    snapPct: 75,
    scheduleRating: 7,
    playoffRating: 7,
  },
  {
    id: 'cole-kmet',
    name: 'Cole Kmet',
    team: 'CHI',
    position: 'TE',
    age: 26,
    bye: 9,
    rank: 89,
    posRank: 10,
    tier: 3,
    adp: 88.0,
    projPts: 138,
    vbd: 20,
    tradeValue: 16,
    injuryRisk: 'Low',
    upside: 'Medium',
    status: 'Active',
    notes: 'Caleb Williams uses him in red zone. Good target share but crowded receiving corps.',
    targetShare: 14,
    snapPct: 72,
    scheduleRating: 7,
    playoffRating: 7,
  },
  {
    id: 'dalton-kincaid',
    name: 'Dalton Kincaid',
    team: 'BUF',
    position: 'TE',
    age: 25,
    bye: 7,
    rank: 101,
    posRank: 11,
    tier: 4,
    adp: 102.0,
    projPts: 128,
    vbd: 10,
    tradeValue: 10,
    injuryRisk: 'Medium',
    upside: 'Medium',
    status: 'Active',
    notes: 'Josh Allen check-down option. Good rapport but crowded WR corps limits targets.',
    targetShare: 13,
    snapPct: 68,
    scheduleRating: 7,
    playoffRating: 8,
  },
  {
    id: 'pat-freiermuth',
    name: 'Pat Freiermuth',
    team: 'PIT',
    position: 'TE',
    age: 26,
    bye: 9,
    rank: 116,
    posRank: 12,
    tier: 4,
    adp: 118.0,
    projPts: 122,
    vbd: 4,
    tradeValue: 7,
    injuryRisk: 'Low',
    upside: 'Medium',
    status: 'Active',
    notes: 'Steady Pittsburgh TE. Streaming option in favorable matchups. Safe floor.',
    targetShare: 14,
    snapPct: 72,
    scheduleRating: 5,
    playoffRating: 5,
  },
  {
    id: 'chigoziem-okonkwo',
    name: 'Chigoziem Okonkwo',
    team: 'TEN',
    position: 'TE',
    age: 25,
    bye: 5,
    rank: 129,
    posRank: 13,
    tier: 4,
    adp: 132.0,
    projPts: 118,
    vbd: 0,
    tradeValue: 5,
    injuryRisk: 'Low',
    upside: 'Medium',
    status: 'Active',
    notes: 'Tennessee pass-catching TE. Streaming/handcuff value in Titans offense.',
    targetShare: 14,
    snapPct: 68,
    scheduleRating: 8,
    playoffRating: 8,
  },

  // ─── DEFENSES ────────────────────────────────────────────────
  {
    id: 'dst-phi',
    name: 'Philadelphia Eagles',
    team: 'PHI',
    position: 'DST',
    age: 0,
    bye: 5,
    rank: 155,
    posRank: 1,
    tier: 1,
    adp: 70.0,
    projPts: 145,
    vbd: 30,
    tradeValue: 15,
    injuryRisk: 'Low',
    upside: 'High',
    status: 'Active',
    notes: 'Elite pass rush with Nolan Smith, Josh Sweat. Top defensive unit in NFC.',
    scheduleRating: 6,
    playoffRating: 7,
  },
  {
    id: 'dst-sf',
    name: 'San Francisco 49ers',
    team: 'SF',
    position: 'DST',
    age: 0,
    bye: 5,
    rank: 156,
    posRank: 2,
    tier: 1,
    adp: 75.0,
    projPts: 140,
    vbd: 25,
    tradeValue: 14,
    injuryRisk: 'Low',
    upside: 'High',
    status: 'Active',
    notes: 'Nick Bosa anchors the best front 7 in football. Elite sack and turnover potential.',
    scheduleRating: 5,
    playoffRating: 5,
  },
  {
    id: 'dst-dal',
    name: 'Dallas Cowboys',
    team: 'DAL',
    position: 'DST',
    age: 0,
    bye: 7,
    rank: 157,
    posRank: 3,
    tier: 2,
    adp: 80.0,
    projPts: 135,
    vbd: 20,
    tradeValue: 12,
    injuryRisk: 'Low',
    upside: 'High',
    status: 'Active',
    notes: 'Micah Parsons is a fantasy weapon himself. Elite upside but can give up points too.',
    scheduleRating: 6,
    playoffRating: 7,
  },
  {
    id: 'dst-bal',
    name: 'Baltimore Ravens',
    team: 'BAL',
    position: 'DST',
    age: 0,
    bye: 7,
    rank: 158,
    posRank: 4,
    tier: 2,
    adp: 85.0,
    projPts: 130,
    vbd: 15,
    tradeValue: 11,
    injuryRisk: 'Low',
    upside: 'High',
    status: 'Active',
    notes: 'Kyle Van Noy, Roquan Smith defense. Ball-hawking secondary creates turnovers.',
    scheduleRating: 5,
    playoffRating: 6,
  },
  {
    id: 'dst-pit',
    name: 'Pittsburgh Steelers',
    team: 'PIT',
    position: 'DST',
    age: 0,
    bye: 9,
    rank: 159,
    posRank: 5,
    tier: 2,
    adp: 88.0,
    projPts: 128,
    vbd: 13,
    tradeValue: 10,
    injuryRisk: 'Low',
    upside: 'High',
    status: 'Active',
    notes: 'Classic Steelers defense. TJ Watt may be the best defensive player in the NFL.',
    scheduleRating: 5,
    playoffRating: 5,
  },
  {
    id: 'dst-ne',
    name: 'New England Patriots',
    team: 'NE',
    position: 'DST',
    age: 0,
    bye: 12,
    rank: 160,
    posRank: 6,
    tier: 2,
    adp: 92.0,
    projPts: 125,
    vbd: 10,
    tradeValue: 9,
    injuryRisk: 'Low',
    upside: 'Medium',
    status: 'Active',
    notes: 'Post-Belichick defense still has talent. Week 12 bye is late-season manageable.',
    scheduleRating: 7,
    playoffRating: 7,
  },
  {
    id: 'dst-nyj',
    name: 'New York Jets',
    team: 'NYJ',
    position: 'DST',
    age: 0,
    bye: 8,
    rank: 161,
    posRank: 7,
    tier: 3,
    adp: 96.0,
    projPts: 120,
    vbd: 5,
    tradeValue: 8,
    injuryRisk: 'Low',
    upside: 'Medium',
    status: 'Active',
    notes: "Quinnen Williams and Sauce Gardner anchor this defense. Good streaming option.",
    scheduleRating: 6,
    playoffRating: 6,
  },
  {
    id: 'dst-kc',
    name: 'Kansas City Chiefs',
    team: 'KC',
    position: 'DST',
    age: 0,
    bye: 11,
    rank: 162,
    posRank: 8,
    tier: 3,
    adp: 100.0,
    projPts: 118,
    vbd: 3,
    tradeValue: 7,
    injuryRisk: 'Low',
    upside: 'Medium',
    status: 'Active',
    notes: 'Spagnuolo schemes well. Chris Jones is a monster. Good value as streaming DST.',
    scheduleRating: 5,
    playoffRating: 5,
  },

  // ─── KICKERS ────────────────────────────────────────────────
  {
    id: 'k-harrison-butker',
    name: 'Harrison Butker',
    team: 'KC',
    position: 'K',
    age: 29,
    bye: 11,
    rank: 170,
    posRank: 1,
    tier: 1,
    adp: 145.0,
    projPts: 162,
    vbd: 40,
    tradeValue: 10,
    injuryRisk: 'Low',
    upside: 'High',
    status: 'Active',
    notes: 'Best kicker in football. KC offense gives him constant FG opportunities.',
    scheduleRating: 5,
    playoffRating: 5,
  },
  {
    id: 'k-jake-elliott',
    name: 'Jake Elliott',
    team: 'PHI',
    position: 'K',
    age: 29,
    bye: 5,
    rank: 171,
    posRank: 2,
    tier: 1,
    adp: 148.0,
    projPts: 155,
    vbd: 33,
    tradeValue: 9,
    injuryRisk: 'Low',
    upside: 'High',
    status: 'Active',
    notes: 'Elite kicker in high-scoring offense. Consistent 50+ yard FG range.',
    scheduleRating: 6,
    playoffRating: 7,
  },
  {
    id: 'k-younghoe-koo',
    name: 'Younghoe Koo',
    team: 'ATL',
    position: 'K',
    age: 30,
    bye: 6,
    rank: 172,
    posRank: 3,
    tier: 2,
    adp: 152.0,
    projPts: 148,
    vbd: 26,
    tradeValue: 8,
    injuryRisk: 'Low',
    upside: 'Medium',
    status: 'Active',
    notes: 'Consistent performer for Falcons. Bijan Robinson helps them score and kick field goals.',
    scheduleRating: 7,
    playoffRating: 6,
  },
  {
    id: 'k-tyler-bass',
    name: 'Tyler Bass',
    team: 'BUF',
    position: 'K',
    age: 27,
    bye: 7,
    rank: 173,
    posRank: 4,
    tier: 2,
    adp: 155.0,
    projPts: 142,
    vbd: 20,
    tradeValue: 7,
    injuryRisk: 'Low',
    upside: 'Medium',
    status: 'Active',
    notes: 'Josh Allen offense gives him plenty of opportunities. Solid but misses occasionally.',
    scheduleRating: 7,
    playoffRating: 8,
  },
]

export const ALL_PLAYERS: Player[] = rawPlayers.map(p => ({
  ...p,
  drafted: false,
  onMyTeam: false,
}))

export function getPlayersByPosition(position: string): Player[] {
  if (position === 'ALL') return ALL_PLAYERS
  return ALL_PLAYERS.filter(p => p.position === position)
}

export function getTopPlayers(count: number): Player[] {
  return ALL_PLAYERS.slice(0, count)
}

export function searchPlayers(query: string): Player[] {
  const q = query.toLowerCase()
  return ALL_PLAYERS.filter(
    p => p.name.toLowerCase().includes(q) || p.team.toLowerCase().includes(q)
  )
}

export const DRAFT_TIPS = [
  'Never reach more than 2 rounds ahead of ADP for any player.',
  'In PPR leagues, WR volume (targets) beats QB passing TDs in value.',
  'Elite TEs (Bowers/Kelce) are scarce — grab one by Round 4 or stream.',
  'Always note bye weeks — avoid stacking 3+ players on the same bye.',
  'Zero-RB works if you nail WRs 1-4 in Rounds 1-6 then grab 3 RBs late.',
  'Hero-RB: Draft 1 elite RB early, stack WRs through Round 6, then RBs.',
  'Best Available Player beats need-based drafting in early rounds.',
  'Watch for positional runs — if 3 QBs go back-to-back, grab your QB next.',
  'Injury risk RBs are fine in Round 3+ if you have a handcuff later.',
  'Playoff schedule (Wks 15-17) matters more than early-season matchups.',
]

export const WAIVER_TIPS = [
  'Spend 75% of FAAB budget in first 8 weeks when impact is highest.',
  'Never go above 30% FAAB for any single player before Week 6.',
  'Stream DST and K every week based on matchup — never spend FAAB.',
  'Injured starter\'s backup is the #1 waiver priority — get them first.',
  'Target players with 20%+ target share immediately after being dropped.',
  'Monitor snap counts — rising snap share predicts future production.',
  'Check injury reports every Thursday for late scratches.',
  'Week 10+ FAAB: if chasing playoffs, spend aggressively on impactful adds.',
]
